sudo: required

language: python

cache:
  directories:
    - $HOME/.cache/pip

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

python:
  - "2.7"

virtualenv:
  system_site_packages: true

branches:
  only:
    - master
    - stand_alone

install:
  - sudo apt-get -qq -y update
  - sudo apt-get install software-properties-common python-software-properties -y
  - sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
  - sudo apt-get -qq -y update
  - sudo apt-get upgrade -y
  - sudo apt-get install -y libgdal1h python-gdal gdal-bin spatialite-bin
  - sudo apt-get install -y python-virtualenv python-imaging python-lxml python-pyproj python-shapely python-nose python-httplib2 python-httplib2 gettext
  - sudo apt-get install -y python-dev libxml2 libxml2-dev libxslt1-dev zlib1g-dev libjpeg-dev libpq-dev libgdal-dev git default-jdk
  - sudo add-apt-repository -y ppa:webupd8team/java
  - sudo apt-get update
  - sudo apt-get install -y --force-yes oracle-java8-installer ant maven2 --no-install-recommends
  - sudo update-java-alternatives --set java-8-oracle
  - pip install -e . --upgrade
  - pip install pygdal==`gdal-config --version`
  - pip install coveralls

script:
  - coverage run --source=cartoview --omit="*/migrations/*,*/apps/*" ./manage.py test

after_success:
  - coveralls

notifications:
  email:
    - hisham.karam@cartologic.com
    - hishamwaleedkaram@gmail.com