sudo: required

language: python

cache:
  directories:
    - $HOME/.cache/pip

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
addons:
  postgresql: "9.6"
  apt:
    packages:
    - postgresql-9.6-postgis-2.3
    - libevent-dev

services:
  - postgresql

python:
  - "2.7"

virtualenv:
  system_site_packages: true

branches:
  only:
    - master
    - stand_alone

install:
  - sudo apt-get -qq -y update
  - sudo apt-get install -y gcc gettext python-pip libpq-dev sqlite3 git gdal-bin lsof psmisc
  - sudo apt-get install -y python-gdal python-psycopg2 python-imaging python-lxml
  - sudo apt-get install -y python-dev libgdal-dev libgeoip-dev python-ldap libxml2 libxml2-dev libxslt-dev git default-jdk
  - sudo apt-get install -y python-dev libxml2 libxml2-dev libxslt1-dev zlib1g-dev libjpeg-dev libpq-dev libgdal-dev git default-jdk
  - sudo apt-get install -y libmemcached-dev libsasl2-dev zlib1g-dev python-pylibmc python-setuptools
  - sudo apt-get install -y curl build-essential build-essential python-dev libffi-dev libssl-dev
  - sudo add-apt-repository -y ppa:webupd8team/java
  - sudo apt-get update
  - sudo apt-get install -y --force-yes oracle-java8-installer ant maven2 --no-install-recommends
  - sudo update-java-alternatives --set java-8-oracle
  - pip install celery
  - pip install pygdal==`gdal-config --version`
  - pip install tqdm
  - pip install -e . --upgrade
  - pip install django-autocomplete-light==2.3.3
  - pip install timeout-decorator
  - paver setup_geoserver
  - paver start_geoserver
  - pip install coveralls

before_script:
  - psql -U postgres -c "create extension postgis"
  - chmod +x scripts/database/setup.sh
  - scripts/database/setup.sh

script:
  - flake8
  - paver run_test

after_success:
  - coveralls

notifications:
  email:
    - hisham.karam@cartologic.com
    - hishamwaleedkaram@gmail.com
    - ahmednosman@cartologic.com
    - ahmedNourElDeen@cartologic.com