---
GEOSERVER_URL: "http://build.geonode.org/geoserver/latest/geoserver-2.13.x.war"
DATA_DIR_URL: "http://build.geonode.org/geoserver/latest/data-2.13.x.zip"
JETTY_RUNNER_URL: "http://repo2.maven.org/maven2/org/eclipse/jetty/jetty-runner/9.4.7.v20170914/jetty-runner-9.4.7.v20170914.jar"