site_name: Cartoview
site_url: https://cartoview.net
repo_url: https://github.com/cartologic/cartoview.git
edit_uri: /docs/
repo_name: Github
site_author: Cartologic
copyright: Cartologic

nav:
  - About: index.md
  - Key Features: key-features.md
  - Demo: demo.md
  - Installation:
      - Ubuntu: installation/ubuntu.md
      - Windows: installation/windows.md
      - Docker: installation/docker.md
theme: readthedocs

extra_css:
    - css/custom.css

markdown_extensions:
    - admonition