site_name: Cartoview
site_url: https://cartoview.net
repo_url: https://github.com/cartologic/cartoview.git
edit_uri: /docs/
repo_name: Github
site_author: Cartologic
copyright: Cartologic

pages:
  - About: index.md
  - Key Features: key-features.md
  - Demo: demo.md
theme: readthedocs